version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:5000" # Maps the backend service to the host's port
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19000:19000" # Expo development server
      - "19001:19001" # Expo debugger
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    env_file:
      - ./.env # Shared project-level environment variables
    ports:
      - "${DB_PORT}:5432" # Maps the database service to the host's port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
